extra_fn_clean_exts:
  - "_R1"
export_plots: true
remove_sections:
  - fastqc_per_sequence_gc_content
  - fastqc_adapter_content
  - fastqc_per_base_sequence_content
  - fastqc_sequence_length_distribution
  - mosdepth-coverage-dist-cov
mosdepth_config:
  general_stats_coverage:
    - 10
    - 30
  exclude_contigs:
    - "*_API_*"
    -  "*_M*"
table_columns_visible:
    mapped_passed_pct: true
